[package]
name = "darkly"
version = "0.2.0"
authors = ["Nick Cameron <nick@ncameron.org>"]
repository = "https://github.com/nrc/darkly"
description = "A simple scanf-style scanner"
license = "Apache-2.0/MIT"

[dependencies]
darkly-macros = "0.2.0"

[[example]]
name = "main"
